---
- name: Generate systemd unit for mounts
  template:
    src: systemd_mount.j2
    dest: "/etc/systemd/system/{{ systemd_mount_filename }}"
    owner: root
    mode: '0644'
  loop: "{{ systemd_mount }}"
  when: systemd_mount is defined
  notify: Enable systemd mount

- name: Generate systemd unit for automounts
  template:
    src: systemd_automount.j2
    dest: "/etc/systemd/system/{{ systemd_automount_filename }}"
    owner: root
    mode: '0644'
  loop: "{{ systemd_automount }}"
  when: systemd_automount is defined
  notify: Enable systemd automount
