---
- name: Generate systemd unit for mounts
  ansible.builtin.template:
    src: systemd_mount.j2
    dest: "/etc/systemd/system/{{ systemd_mount_filename }}"
    owner: root
    mode: "0644"
  vars:
    - current_options: "{{ systemd_mount_options }}"
    - current_type: systemd.mount
  loop: "{{ systemd_mount }}"
  notify: Enable systemd mount

- name: Generate systemd unit for automounts
  ansible.builtin.template:
    src: systemd_mount.j2
    dest: "/etc/systemd/system/{{ systemd_automount_filename }}"
    owner: root
    mode: "0644"
  vars:
    - current_options: "{{ systemd_automount_options }}"
    - current_type: systemd.automount
  loop: "{{ systemd_automount }}"
  notify: Enable systemd automount
